server:
  host: 192.168.12.179
  port: 5001

client:
  host: 192.168.12.179
  port: 5001

colors:
  server: yellow
  client: cyan

specials:
  breakers: ['quit', 'exit', 'bye', 'close', 'end', 'stop', 'kill', 'leave']

commands:
  prefix: "!"
  help: ['help']
  simulation: ['simulate', 'simulation']
  file_send: ['share-code', 'send', 'share', 'upload', 'code review']
  file_edit: ['edit-code', 'code', 'open', 'editor', 'edit', 'vim', 'micro', 'nano']

settings:
  max_connections: 10
  timeout: 30
