server:
  host: 0.0.0.0
  port: 5001

client:
  host: 159.89.178.145
  port: 5001

colors:
  server: yellow
  client: cyan

breakers:
  values: ['quit', 'exit', 'bye', 'close', 'end', 'stop', 'kill', 'leave']

settings:
  max_connections: 10
  timeout: 30
